In [1]:
#import liberaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#import dataset
data=pd.read_csv("dataset.txt")

In [3]:
data

Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
0       1-01-2017  Sunday         7     1       21           17        1
1       1-01-2017  Sunday         7     2       12           34        2
2       1-01-2017  Sunday         7     3       25           24        2
3       1-01-2017  Sunday         7     4       46           41        4
4       1-01-2017  Sunday         7     5       33           19        3
...           ...     ...       ...   ...      ...          ...      ...
53850  10-06-2018  Friday         5   140       47           38        1
53851  10-06-2018  Friday         5   141       15            8        4
53852  10-06-2018  Friday         5   142       26           38        1
53853  10-06-2018  Friday         5   143       16           34        3
53854  10-06-2018  Friday         5   144       16           17        1

[53855 rows x 7 columns]

In [4]:
data.head

<bound method NDFrame.head of              Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
0       1-01-2017  Sunday         7     1       21           17        1
1       1-01-2017  Sunday         7     2       12           34        2
2       1-01-2017  Sunday         7     3       25           24        2
3       1-01-2017  Sunday         7     4       46           41        4
4       1-01-2017  Sunday         7     5       33           19        3
...           ...     ...       ...   ...      ...          ...      ...
53850  10-06-2018  Friday         5   140       47           38        1
53851  10-06-2018  Friday         5   141       15            8        4
53852  10-06-2018  Friday         5   142       26           38        1
53853  10-06-2018  Friday         5   143       16           34        3
53854  10-06-2018  Friday         5   144       16           17        1

[53855 rows x 7 columns]>

In [5]:
data.tail(10)

Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
53845  10-06-2018  Friday         5   135       18           25        4
53846  10-06-2018  Friday         5   136       31            8        2
53847  10-06-2018  Friday         5   137       13           11        4
53848  10-06-2018  Friday         5   138       34           15        1
53849  10-06-2018  Friday         5   139        5           43        4
53850  10-06-2018  Friday         5   140       47           38        1
53851  10-06-2018  Friday         5   141       15            8        4
53852  10-06-2018  Friday         5   142       26           38        1
53853  10-06-2018  Friday         5   143       16           34        3
53854  10-06-2018  Friday         5   144       16           17        1

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53855 entries, 0 to 53854
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Date         53855 non-null  object
 1   Day          53855 non-null  object
 2   CodedDay     53855 non-null  int64 
 3   Zone         53855 non-null  int64 
 4   Weather      53855 non-null  int64 
 5   Temperature  53855 non-null  int64 
 6   Traffic      53855 non-null  int64 
dtypes: int64(5), object(2)
memory usage: 2.9+ MB


In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le= LabelEncoder()

In [9]:
data['Date']=le.fit_transform(data['Date'])
data

Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
0         0  Sunday         7     1       21           17        1
1         0  Sunday         7     2       12           34        2
2         0  Sunday         7     3       25           24        2
3         0  Sunday         7     4       46           41        4
4         0  Sunday         7     5       33           19        3
...     ...     ...       ...   ...      ...          ...      ...
53850    19  Friday         5   140       47           38        1
53851    19  Friday         5   141       15            8        4
53852    19  Friday         5   142       26           38        1
53853    19  Friday         5   143       16           34        3
53854    19  Friday         5   144       16           17        1

[53855 rows x 7 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53855 entries, 0 to 53854
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Date         53855 non-null  int32 
 1   Day          53855 non-null  object
 2   CodedDay     53855 non-null  int64 
 3   Zone         53855 non-null  int64 
 4   Weather      53855 non-null  int64 
 5   Temperature  53855 non-null  int64 
 6   Traffic      53855 non-null  int64 
dtypes: int32(1), int64(5), object(1)
memory usage: 2.7+ MB


In [17]:
x=data.iloc[:,2:6].values
y=data.iloc[:,6:7].values

In [18]:
x

array([[  7,   1,  21,  17],
       [  7,   2,  12,  34],
       [  7,   3,  25,  24],
       ...,
       [  5, 142,  26,  38],
       [  5, 143,  16,  34],
       [  5, 144,  16,  17]], dtype=int64)

In [19]:
x.shape

(53855, 4)

In [20]:
y

array([[1],
       [2],
       [2],
       ...,
       [1],
       [3],
       [1]], dtype=int64)

In [21]:
y.shape

(53855, 1)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.20, random_state=0)

In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((43084, 4), (10771, 4), (43084, 1), (10771, 1))

In [26]:
#feature scaling for normalizing the data
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler()

In [28]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [29]:
x_train

array([[-0.50328978, -0.89977971,  1.63173364,  1.50876306],
       [-0.50328978,  0.88153753, -0.25265695,  1.50876306],
       [-0.50328978, -0.851636  , -1.26732881, -1.69056234],
       ...,
       [-1.50626102,  1.48333389, -0.97742257,  1.16289004],
       [-1.50626102,  0.18345375, -0.18018039,  0.12527099],
       [-0.00180416,  1.65183688,  1.26935084, -1.34468933]])

In [30]:
#random forest
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=300,random_state=0)

In [31]:
regressor.fit(x_train,y_train)

<ipython-input-31-923b4e1a10f6>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300, random_state=0)

In [32]:
y_pred=regressor.predict(x_test)

In [33]:
y_pred

array([3.24666667, 3.30333333, 3.42666667, ..., 2.25222222, 3.52      ,
       2.99666667])

In [34]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)
y_pred

array([3., 3., 3., ..., 2., 3., 2.])

In [35]:
df=(y_pred-y_test)/y_test
df=round(df.mean()*100,2)
print("Error= ", df,"%")

Error=  13.43 %


In [36]:
acc = 100-df
print("Accuracy= ", acc,"%")

Accuracy=  86.57 %


In [37]:
#SVM(Support Vector Machine)
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)
y_pred

C:\Users\satwi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([2.94814622, 3.02676688, 2.93469726, ..., 2.94603306, 2.95457788,
       3.01643261])

In [38]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)
y_pred

array([2., 3., 2., ..., 2., 2., 3.])

In [39]:
df=(y_pred-y_test)/y_test
df=round(df.mean()*100,2)
print("Error= ", df,"%")

Error=  11.29 %


In [40]:
acc = 100-df
print("Accuracy= ", acc,"%")

Accuracy=  88.71000000000001 %
